//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrgProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class AllUserData
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AllUserData()
        {
            this.CoursesWithYears = new HashSet<CoursesWithYear>();
            this.FinalMasters = new HashSet<FinalMaster>();
            this.FinalProjects = new HashSet<FinalProject>();
            this.FinalProjects1 = new HashSet<FinalProject>();
            this.ProjectToSubmitDoctors = new HashSet<ProjectToSubmitDoctor>();
            this.ProjectToSubmitDoctors1 = new HashSet<ProjectToSubmitDoctor>();
        }
    
        public int id { get; set; }

        [Required(ErrorMessage = "Required First Name", AllowEmptyStrings = false)]
        [Display(Name = "First Name")]
        public string F_Name { get; set; }

        [Required(ErrorMessage = "Required Last Name", AllowEmptyStrings = false)]
        [Display(Name = "Last Name")]
        public string L_Name { get; set; }

        [Required(ErrorMessage = "Required Email", AllowEmptyStrings = false)]
        [DataType(DataType.EmailAddress, ErrorMessage = "This Is Not Email Address")]
        public string Email { get; set; }

        [Required(ErrorMessage = "Required Password", AllowEmptyStrings = false)]
        [DataType(DataType.Password)]
        [MinLength(9, ErrorMessage = "Min Is 9")]
        public string Password { get; set; }

        [Display(Name = "Type Name")]
        public Nullable<int> type_id { get; set; }

        [Display(Name = "Department Name")]
        public Nullable<int> Dep_id { get; set; }
    
        public virtual Departement_Name Departement_Name { get; set; }
        public virtual Type Type { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CoursesWithYear> CoursesWithYears { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FinalMaster> FinalMasters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FinalProject> FinalProjects { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FinalProject> FinalProjects1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectToSubmitDoctor> ProjectToSubmitDoctors { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectToSubmitDoctor> ProjectToSubmitDoctors1 { get; set; }
    }
}
