//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrgProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class CoursesWithYear
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CoursesWithYear()
        {
            this.Questions = new HashSet<Question>();
        }
    
        public int id { get; set; }

        [Required(ErrorMessage = "Required Name Of Cource")]
        [Display(Name = "Name Of Course")]
        public string NameOfCource { get; set; }

        [Display(Name = "Doctor Name")]
        public Nullable<int> Doc_id { get; set; }

        [Display(Name = "Year Of Course")]
        public Nullable<int> YearOfThisCource { get; set; }
        public string Deaprtment { get; set; }
        public string Term { get; set; }
    
        public virtual AllUserData AllUserData { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Question> Questions { get; set; }
    }
}
