//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrgProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class GuideYear
    {
        public int id { get; set; }

        //[Required(ErrorMessage = "Required Header")]
        [Display(Name = "Header Of Year")]
        public Nullable<int> HeaderOFYear { get; set; }

        [Required(ErrorMessage = "Required Article")]
        public string Article { get; set; }

        [Required(ErrorMessage = "Required This Link")]
        public string Link1 { get; set; }
        public string Link2 { get; set; }
        public string Link3 { get; set; }
        public string Link4 { get; set; }
    }
}
