//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrgProject.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MyDBEntities : DbContext
    {
        public MyDBEntities()
            : base("name=MyDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AllUserData> AllUserDatas { get; set; }
        public virtual DbSet<ChatMessageDetail> ChatMessageDetails { get; set; }
        public virtual DbSet<ChatPrivateMessageDetail> ChatPrivateMessageDetails { get; set; }
        public virtual DbSet<ChatPrivateMessageMaster> ChatPrivateMessageMasters { get; set; }
        public virtual DbSet<ChatUserDetail> ChatUserDetails { get; set; }
        public virtual DbSet<Comment> Comments { get; set; }
        public virtual DbSet<CoursesWithYear> CoursesWithYears { get; set; }
        public virtual DbSet<Departement_Name> Departement_Name { get; set; }
        public virtual DbSet<FinalMaster> FinalMasters { get; set; }
        public virtual DbSet<FinalProject> FinalProjects { get; set; }
        public virtual DbSet<ProjectToSubmitDoctor> ProjectToSubmitDoctors { get; set; }
        public virtual DbSet<Question> Questions { get; set; }
        public virtual DbSet<Reply> Replies { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Type> Types { get; set; }
        public virtual DbSet<GuideYear> GuideYears { get; set; }
    }
}
