//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrgProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class ProjectToSubmitDoctor
    {
        public int id { get; set; }

        [Required(ErrorMessage = "Name Of Project Is Required")]
        [Display(Name = "Name Of Project")]
        public string NameOfProject { get; set; }

        [Required(ErrorMessage = "Descrpition Is Required")]
        public string Description { get; set; }

        [Required(ErrorMessage = "Names Of Team Is Required")]
        [Display(Name = "Names Of Team ")]
        public string Names { get; set; }


        public bool IsActive { get; set; }
        public string ThisStudent { get; set; }

        [Display(Name = "Doctor Name")]
        public Nullable<int> Doc_Id { get; set; }

        [Display(Name = "Department Name")]
        public Nullable<int> Dep_id { get; set; }

        [Display(Name = "Doctor Name")]
        public Nullable<int> TeachAss_id { get; set; }
    
        public virtual AllUserData AllUserData { get; set; }
        public virtual AllUserData AllUserData1 { get; set; }
        public virtual Departement_Name Departement_Name { get; set; }
    }
}
