//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrgProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Question
    {
        public int Id { get; set; }

        [Required(ErrorMessage = "Required Question Name")]
        [Display(Name = "Question Name")]
        public string Qu_Name { get; set; }

        //[Required(ErrorMessage = "Required Answer 1")]
        [Display(Name = "Answer 1")]
        public string Answer_1 { get; set; }

        //[Required(ErrorMessage = "Required Answer 2")]
        [Display(Name = "Answer 2")]
        public string Answer_2 { get; set; }

        //[Required(ErrorMessage = "Required Answer 3")]
        [Display(Name = "Answer 3")]
        public string Answer_3 { get; set; }

        //[Required(ErrorMessage = "Required Answer 4")]
        [Display(Name = "Answer 4")]
        public string Answer_4 { get; set; }

        [Display(Name = "Correct Answer")]
        public string Answer_Correct { get; set; }

        [Display(Name = "Course Name")]
        public Nullable<int> Course_id { get; set; }
    
        public virtual CoursesWithYear CoursesWithYear { get; set; }
    }
}
